export const LOGIN_ADMIN_USER = "LOGIN_ADMIN_USER";
export const LOGOUT_ADMIN_USER = "LOGOUT_ADMIN_USER";
export const FAIL_LOGIN_USER = "FAIL_LOGIN_USER";
export const FAIL_LOGOUT_USER = "FAIL_LOGOUT_USER";